version: 2.1

orbs:
  win: circleci/windows@5.0.0
  node: circleci/node@5.1.0

commands:
  build:
    parameters:
      env:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci_build/
      - run:
          name: Install node
          command: "nvm install 16"
      - run:
          name: Set node version
          command: "nvm use 16"
      - run:
          name: Install yarn
          command: "npm install -g yarn"
      - run:
          name: "Install dependencies"
          command: "yarn"
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: "Lint, prettier .."
          command: "yarn verify"
      - run:
          name: "Build Production Assets"
          command: "yarn build:prod"
      - run:
          name: "Build Production Package"
          command: "yarn makeInstaller:<<parameters.env>>"
      - run:
          name: "Create release archive"
          command: |
            tar cvf DROP.tar.gz -C ./public .
            tar rvf DROP.tar.gz ./pkg
          shell: bash.exe
      - store_artifacts:
          path: ~/ci_build/DROP.tar.gz
          destination: DROP.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - DROP.tar.gz

  deploy:
    parameters:
      cloud_bucket:
        type: string
    steps:
      - attach_workspace:
          at: ~/ci_build/
      - run:
          name: "Deployment information"
          command: |
            echo "Deploying Build $CIRCLE_BUILD_NUM"
      - run:
          name: Authenticate with gcloud
          command: |
            echo $BASH_ENV
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Delete GCS Bucket Contents
          command: |
            gsutil -m rm 'gs://<<parameters.cloud_bucket>>/**'
      - run:
          name: Copy artifacts to GCS
          command: |
            cd ~/ci_build/
            tar -xvf DROP*.tar.gz
            rm DROP*.tar.gz
            gsutil -m cp -r * gs://<<parameters.cloud_bucket>>

jobs:
  build_uat:
    executor: win/default
    working_directory: ~/ci_build
    steps:
      - build:
          env: "uat"

  build_prod:
    executor: win/default
    working_directory: ~/ci_build
    steps:
      - build:
          env: "prod"

  deploy_uat:
    description: "Deploy Artifacts to UAT GCS"
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy:
          cloud_bucket: "reactive-trader-finsemble-uat"

  deploy_prod:
    description: "Deploy Artifacts to production GCS"
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy:
          cloud_bucket: "reactive-trader-finsemble"

workflows:
  version: 2
  UAT_Workflow:
    jobs:
      - build_uat
      - deploy_uat:
          requires:
            - build_uat
          filters:
            branches:
              only: master

  Prod_Workflow:
    jobs:
      - build_prod
      - hold_deploy_prod:
          type: approval
          requires:
            - build_prod
          filters:
            branches:
              only: master
      - deploy_prod:
          requires:
            - hold_deploy_prod
