version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor: win/default
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: 'Authenticate with registry'
          command: 'echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/repo/.npmrc'
          shell: bash.exe
      - run:
          name: 'Install NPM Packages'
          command: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Lint'
          command: 'yarn eslint'
      - run:
          name: 'Build Production Assets'
          command: 'yarn build:prod'
      - run:
          name: 'Move Production Assets'
          command: 'yarn deploy'
      - run:
          name: 'Build Production Package'
          command: 'yarn makeInstaller:prod'
      - store_artifacts:
          path: ~/repo/pkg/
          destination: /pkg/
      - store_artifacts:
          path: ~/repo/docs/
          destination: /docs/
