version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    working_directory: ~/ci_build
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: docs/
      - run:
          name: 'Authenticate with registry'
          command: 'echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/ci_build/.npmrc'
          shell: bash.exe
      - run:
          name: 'Install NPM Packages'
          command: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Lint'
          command: 'yarn eslint'
      - run:
          name: 'Build Production Assets'
          command: 'yarn build:prod'
      - run:
          name: 'Move Production Assets'
          command: 'yarn deploy'
      #   - run:
      #       name: 'Build Production Package'
      #       command: 'yarn makeInstaller:prod'
      - run:
          name: 'Zip and Create Docs'
          command: tar -cvf DOCS.tar.gz -C ~/ci_build/docs .
          shell: bash.exe
      - store_artifacts:
          path: ~/ci_build/DOCS.tar.gz
          destination: DOCS.tar.gz
      - store_artifacts:
          path: ~/ci_build/pkg/ReactiveTraderFinsembleSetup.exe
          destination: ReactiveTraderFinsembleSetup.exe

  deploy:
    description: 'Deploy Artifacts to GCS'
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: ~/ci_build/
      - run:
          name: 'Deployment information'
          command: |
            echo "Deploying $CIRCLE_BUILD_NUM"
            echo "ls"
      - run:
          name: Authenticate with gcloud
          command: |
            echo $BASH_ENV
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project ${GOOGLE_PROJECT_ID}
            gsutil -m cp -r * gs://reactive-trader-finsemble

workflows:
  version: 2
  Main_Workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: gcs
