version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  pullinstaller:
    description: "Pull current installer from GCS"
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Authenticate with gcloud
          command: |
            echo $BASH_ENV
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Copy installer from GCS
          command: "gsutil -m cp -r gs://reactive-trader-finsemble-test/pkg ."
      - persist_to_workspace:
          root: .
          paths:
            - pkg
      
  build:
    executor: win/default
    working_directory: ~/ci_build
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci_build/
      - run:
        name: "Debug 1"
        command: "ls ~/ci_build/pkg"
      - run:
          name: "Authenticate with registry"
          command: 'echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/ci_build/.npmrc'
          shell: bash.exe
      - run:
          name: "Install NPM Packages"
          command: "yarn install"
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: "Lint"
          command: "yarn eslint"
      - run:
          name: "Build Production Assets"
          command: "yarn build:prod"
      - run:
          name: "Move Production Assets"
          command: "yarn deploy"
      - run:
          name: "Build Production Package"
          command: "yarn makeInstaller:prod"
      - run:
          name: "Add Installer to Production Assets"
          command: "cp -r ~/ci_build/pkg ~/ci_build/docs"
      - run:
          name: "Zip and Create DROP"
          command: tar -cvf DROP.tar.gz -C ~/ci_build/docs .
          shell: bash.exe
      - store_artifacts:
          path: ~/ci_build/DROP.tar.gz
          destination: DROP.tar.gz
      - store_artifacts:
          path: ~/ci_build/pkg/ReactiveTraderFinsemble.exe
          destination: ReactiveTraderFinsemble.exe
      - persist_to_workspace:
          root: .
          paths:
            - DROP.tar.gz

  deploy:
    description: "Deploy Artifacts to GCS"
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: ~/ci_build/
      - run:
          name: "Deployment information"
          command: |
            echo "Deploying Build $CIRCLE_BUILD_NUM"
      - run:
          name: Authenticate with gcloud
          command: |
            echo $BASH_ENV
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Delete GCS Bucket Contents
          command: |
            gsutil -m rm 'gs://reactive-trader-finsemble/**'
      - run:
          name: Copy artifacts to GCS
          command: |
            cd ~/ci_build/
            tar -xvf DROP*.tar.gz
            gsutil -m cp -r * gs://reactive-trader-finsemble

workflows:
  version: 2
  Main_Workflow:
    jobs:
      - pullinstaller
      - build:
          requires:
            - pullinstaller
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master